/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package advent_of_code_2021;


import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.net.URISyntaxException;
import java.util.List;

import static org.assertj.core.api.Assertions.*;
class DayOneTest {
    @Test
    void part1() throws IOException, URISyntaxException {
        DayOne classUnderTest = new DayOne();
        List<String> input = Utils.readInputLinesFromFile("day_one.txt");

        assertThat(classUnderTest.findNumberIncreased(input)).isEqualTo(1759);
    }


    @Test
    void part2() throws IOException, URISyntaxException {
        DayOne classUnderTest = new DayOne();
        List<String> input = Utils.readInputLinesFromFile("day_one.txt");

        assertThat(classUnderTest.findNumberIncreasedWindow(input)).isEqualTo(1805);
    }

}
