/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package advent_of_code_2021;


import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import static org.assertj.core.api.Assertions.*;
class LibraryTest {
    @Test
    void testSomeLibraryMethod() throws IOException {
        Library classUnderTest = new Library();
        List<String> input = Files.lines(Paths.get("/Users/alec.tunbridge/IdeaProjects/advent_of_code_2021/src/test/resources/day_one.txt")).collect(Collectors.toList());

        assertThat(classUnderTest.findNumberIncreased(input)).isEqualTo(1759);
    }


    @Test
    void part2() throws IOException {
        Library classUnderTest = new Library();
        List<String> input = Files.lines(Paths.get("/Users/alec.tunbridge/IdeaProjects/advent_of_code_2021/src/test/resources/day_one.txt")).collect(Collectors.toList());

        assertThat(classUnderTest.findNumberIncreasedWindow(input)).isEqualTo(1805);
    }

}
